<?php
	/**
	*	Seria TV Welcome page
	*/
	require_once(dirname(__FILE__)."/common.php");
	$gui->activeMenuItem('esiFrontend');
        SERIA_Base::viewMode("admin");

	$gui->contents('<h1 class="legend">'._t("Seria ESI Frontend")."</h1>
<p>"._t("The Seria ESI Frontend application parses the output generated by the configured backend for ESI-tags and handles them correctly. It integrates with authentication and allows third party includes to integrate with your website securely.")."</p>");


	echo $gui->output();
	
	
