<?php
/**
* Automatically generated by scripts/scaffold.php. Please modify it to suit your needs.
*/
require(dirname(__FILE__)."/../../../main.php");
SERIA_Base::pageRequires("admin");

if(empty($_GET['id']) || empty($_GET['ns']))
{
	SERIA_Base::redirectTo(SERIA_HTTP_ROOT.'/seria/components/SERIA_Privileges/pages/');
}

/**
* Build page contents
*/
$privileges = SERIA_Privileges::getApplicationPrivileges();
if(empty($privileges[$_GET['ns']]))
{
	SERIA_Base::displayErrorPage('404', _t("No such application ID"), _t("The application ID specified in the URL is not installed on this system. If you found this page via a link in the management system, then you probably discovered a bug. Please report it."));
}
else
{
	$appInfo = $privileges[$_GET['ns']];
}

if(empty($appInfo['privileges'][$_GET['id']]))
{
	SERIA_Base::displayErrorPage('404', _t("No such privilege"), _t("The privilege specified in the URL is not available for the <strong>%APPLICATION%</strong> application. If you found this page via a link in the management system, then you probably discovered a bug. Please report it.", array('APPLICATION' => $appInfo['displayName'])));
}
else
{
	$gui = new SERIA_Gui(_t("%APPLICATION% - privileges", array('APPLICATION' => $appInfo['displayName'])));
	$gui->activeMenuItem("controlpanel/users/privileges");

	$privileges = new SERIA_Privileges($_GET['ns']);

	$contents = "<h1 class=\"legend\">"._t("%APPLICATION% - privileges", array('APPLICATION' => $appInfo['displayName']))."</h1>";

	$contents .= "<h2>".$appInfo['privileges'][$_GET['id']][0]."</h2>";
	$contents .= "<p>".$appInfo['privileges'][$_GET['id']][1]."</p>";

	$contents .= "<table style='width:100%'><thead><th>"._t("Users with the privilege")."</th><th>&nbsp;</th><th>"._t("Users without the privilege")."</th></tr></thead><tbody><tr><td>";

	$users = $privileges->getUsersHaving($_GET['id']);
	$users->order('display_name');
	$li = array();
	foreach($users as $user)
	{
		$action = $privileges->revokePrivilegeAction($_GET['id'], $user);
		if($action->success)
		{
			SERIA_Base::redirectTo(SERIA_Url::current()->removeParam('revoke_privilege'));
		}
		$li[] = '<li><a href="'.$action.'">'.$user->get('display_name').'</a> ('.$user->get('email').')</li>';
	}
	if(sizeof($li)>0)
		$contents .= '<ul>'.implode('',$li).'</ul>';
	else
		$contents .= '<p>No users have this privilege</p>';


	$contents .= "</td><td>";
	$contents .= "</td><td>";

	$users = $privileges->getUsersNotHaving($_GET['id']);
	$li = array();
	foreach($users as $user)
	{
		$action = $privileges->grantPrivilegeAction($_GET['id'], $user);
		if($action->success)
		{
			SERIA_Base::redirectTo(SERIA_Url::current()->removeParam('grant_privilege'));
		}
		$li[] = '<li><a href="'.$action.'">'.$user->get('display_name').'</a> ('.$user->get('email').')</li>';
	}
	if(sizeof($li)>0)
		$contents .= '<ul>'.implode('',$li).'</ul>';
	else
		$contents .= '<p>All users have this privilege</p>';



	$contents .= "</td></tbody></table>";

}
/**
* Output page to the end user
*/
echo $gui->contents($contents)->output();
/*
array(1) {
  ["SERIA_Privileges"]=>
  array(2) {
    ["displayName"]=>
    string(15) "User privileges"
    ["privileges"]=>
    array(2) {
      ["access"]=>
      string(20) "View user privileges"
      ["modify"]=>
      string(22) "Manage user privileges"
    }
  }
}
*/
