<?php
/**
* Automatically generated by scripts/scaffold.php. Please modify it to suit your needs.
*/
require(dirname(__FILE__)."/../../../main.php");
SERIA_Base::pageRequires("admin");

$gui = new SERIA_Gui(_t("Privileges"));
$gui->activeMenuItem("controlpanel/users/privileges");

$contents = "<h1 class=\"legend\">"._t("Privileges")."</h1>";
$contents .= "<p class=\"description\">"._t("Manage user privileges")."</p>";

/**
* Build page contents
*/
$privileges = SERIA_Privileges::getApplicationPrivileges();
$sections = array();
foreach($privileges as $applicationName => $info)
{
	$section = '<div style="float:left; width: 200px;"><h2>'.$info['displayName'].'</h2>';
	$items = array();
	foreach($info['privileges'] as $key => $privilegeInfo)
	{
		$items[] = '<li><a href="'.SERIA_HTTP_ROOT.'/seria/components/SERIA_Privileges/pages/edit.php?ns='.rawurlencode($applicationName).'&id='.rawurlencode($key).'" title="'.htmlspecialchars($privilegeInfo[1]).'">'.$privilegeInfo[0].'</a></li>';
	}
	$section .= '<ul>'.implode('', $items).'</ul>';
	$section .= "</div>";
	$sections[] = $section;
}

foreach($sections as $section)
	$contents .= $section;

$contents .= "<div style='clear:both'></div>";


/**
* Output page to the end user
*/
echo $gui->contents($contents)->output();
/*
array(1) {
  ["SERIA_Privileges"]=>
  array(2) {
    ["displayName"]=>
    string(15) "User privileges"
    ["privileges"]=>
    array(2) {
      ["access"]=>
      string(20) "View user privileges"
      ["modify"]=>
      string(22) "Manage user privileges"
    }
  }
}
*/
